/** AUTOGENERATED CODE BY GHOSTGRAPH CODEGEN **/

// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

struct UnpausedEvent {
    address account;
}

struct UnclaimedRewardsWithdrawnEvent {
    uint256 campaignId;
    uint256 amount;
    address recipient;
}

struct TotalRewardsClaimedEvent {
    address user;
    uint256 totalAmount;
}

struct TokenWhitelistedEvent {
    address token;
}

struct TokenWhitelistRemovedEvent {
    address token;
}

struct RoleRevokedEvent {
    bytes32 role;
    address account;
    address sender;
}

struct RoleGrantedEvent {
    bytes32 role;
    address account;
    address sender;
}

struct RoleAdminChangedEvent {
    bytes32 role;
    bytes32 previousAdminRole;
    bytes32 newAdminRole;
}

struct RewardsClaimedEvent {
    address user;
    uint256 campaignId;
    uint256 amount;
}

struct RewardTokensWithdrawnEvent {
    uint256 campaignId;
    address recipient;
    uint256 amount;
}

struct RewardTokensDepositedEvent {
    uint256 campaignId;
    address depositor;
    uint256 amount;
}

struct ReferralMadeEvent {
    address referrer;
    address referee;
    uint256 lpTokenAmount;
}

struct ReferralFailedEvent {
    address referrer;
    address referee;
    string reason;
}

struct PausedEvent {
    address account;
}

struct MinLpTokenAmountUpdatedEvent {
    address lpToken;
    uint256 amount;
}

struct MaxRewardRateIncreasedEvent {
    uint256 campaignId;
    uint256 newMaxRate;
}

struct GlobalRootUpdatedEvent {
    bytes32 newRoot;
    uint256 updateTimestamp;
}

struct ChangeProposedEvent {
    string changeType;
    uint256 newValue;
    uint256 effectiveTime;
}

struct ChangeExecutedEvent {
    string changeType;
    uint256 newValue;
}

struct CampaignCreatedEvent {
    uint256 campaignId;
    address creator;
    address rewardToken;
    address lpToken;
    uint256 maxRewardRate;
    uint256 startTimestamp;
    uint256 endTimestamp;
    uint256 totalRewards;
}